package dukey;

import java.io.ByteArrayOutputStream;
import java.io.FileNotFoundException;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.util.Scanner;

import dukey.command.Command;
import dukey.exception.DukeyException;
import dukey.parser.Parser;
import dukey.storage.Storage;
import dukey.task.TaskList;
import dukey.ui.Ui;

/**
 * Runs the Dukey chatbot application.
 */
public class Dukey {
    private Storage storage;
    private TaskList tasks;
    private Ui ui;
    private Parser parser;
    private boolean isExit;

    /**
     * Creates a Dukey chatbot that loads and saves tasks at the given file path.
     *
     * @param filePath Path to the task data file.
     */
    public Dukey(String filePath) {
        this(filePath, true);
    }

    /**
     * Creates a Dukey chatbot that loads and saves tasks at the given file path.
     *
     * @param filePath Path to the task data file.
     * @param shouldShowWelcome Whether to print the welcome message immediately.
     */
    public Dukey(String filePath, boolean shouldShowWelcome) {
        this.ui = new Ui();
        this.parser = new Parser();
        this.isExit = false;

        if (shouldShowWelcome) {
            this.ui.showWelcome();
        }

        this.storage = new Storage(filePath);
        try {
            this.tasks = storage.load();
        } catch (FileNotFoundException e) {
            this.ui.showLoadingError();
            this.tasks = new TaskList();
        } catch (DukeyException e) {
            this.ui.showError(e.getMessage());
            this.tasks = new TaskList();
        }
    }

    /**
     * Starts the command loop and processes user commands until the user exits.
     */
    public void run() {
        Scanner scanner = new Scanner(System.in);

        while (!this.isExit && scanner.hasNextLine()) {
            String userInput = scanner.nextLine();

            this.ui.showLine();

            try {
                Command command = this.parser.parse(userInput);
                command.execute(this.tasks, this.ui, this.storage);
                this.isExit = command.isExit();
            } catch (DukeyException e) {
                this.ui.showError(e.getMessage());
            }

            this.ui.showLine();
        }
    }

    /**
     * Processes one command and returns the response text.
     *
     * @param userInput Command entered by the user.
     * @return Response generated by Dukey.
     */
    public String getResponse(String userInput) {
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        Ui responseUi = new Ui(new PrintStream(outputStream, true, StandardCharsets.UTF_8));

        try {
            Command command = this.parser.parse(userInput);
            command.execute(this.tasks, responseUi, this.storage);
            this.isExit = command.isExit();
        } catch (DukeyException e) {
            responseUi.showError(e.getMessage());
        }

        return outputStream.toString(StandardCharsets.UTF_8).trim();
    }

    /**
     * Returns whether Dukey has received an exit command.
     *
     * @return true if Dukey should stop accepting commands.
     */
    public boolean isExit() {
        return this.isExit;
    }

    /**
     * Starts the chatbot application.
     *
     * @param args Command line arguments supplied by the runtime.
     */
    public static void main(String[] args) {
        new Dukey("src/main/data/dukey.txt").run();
    }
}
