package dukey.gui;

import java.io.IOException;
import java.util.Collections;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.HBox;

/**
 * Displays one message bubble with the speaker's image.
 */
public class DialogBox extends HBox {
    @FXML
    private Label dialog;
    @FXML
    private ImageView displayPicture;

    private DialogBox(String text, Image image) {
        try {
            FXMLLoader fxmlLoader = new FXMLLoader(MainWindow.class.getResource("/view/DialogBox.fxml"));
            fxmlLoader.setController(this);
            fxmlLoader.setRoot(this);
            fxmlLoader.load();
        } catch (IOException e) {
            e.printStackTrace();
        }

        dialog.setText(text);
        displayPicture.setImage(image);
    }

    /**
     * Creates a dialog box for a user message.
     *
     * @param text Text entered by the user.
     * @param image User avatar.
     * @return Dialog box showing the user's message.
     */
    public static DialogBox getUserDialog(String text, Image image) {
        return new DialogBox(text, image);
    }

    /**
     * Creates a dialog box for a Dukey response.
     *
     * @param text Text generated by Dukey.
     * @param image Dukey avatar.
     * @return Dialog box showing Dukey's response.
     */
    public static DialogBox getDukeyDialog(String text, Image image) {
        return getDukeyDialog(text, image, CommandStyle.DEFAULT);
    }

    /**
     * Creates a dialog box for a styled Dukey response.
     *
     * @param text Text generated by Dukey.
     * @param image Dukey avatar.
     * @param styleClass CSS class used to style the response bubble.
     * @return Dialog box showing Dukey's styled response.
     */
    public static DialogBox getDukeyDialog(String text, Image image, String styleClass) {
        DialogBox dialogBox = new DialogBox(text, image);
        dialogBox.flip();
        dialogBox.applyResponseStyle(styleClass);
        return dialogBox;
    }

    private void applyResponseStyle(String styleClass) {
        dialog.getStyleClass().add(styleClass);
    }

    private void flip() {
        ObservableList<Node> children = FXCollections.observableArrayList(this.getChildren());
        Collections.reverse(children);
        getChildren().setAll(children);
        setAlignment(Pos.TOP_LEFT);
        dialog.getStyleClass().add("reply-label");
    }

    private static class CommandStyle {
        private static final String DEFAULT = "default-response-label";
    }
}
